### PR TITLE
martian

### PR DESCRIPTION
**Pull request by Nino55N**
@sammygutierrez @mseipel @dnguyenchevy @PhilipRead 
plz +1

### CODE REVIEW

**Comment by PhilipRead** [comment]
Is that out on DVD yet?

**Comment by Nino55N** [comment]
@PhilipRead it will be when we get there disco-parrot

**Comment by PhilipRead** [comment]
I don't know. I'm gonna need this signed off by at least 4 managers to approve.

**Comment by Nino55N** [comment]
@PhilipRead sammy counts as CEO of ALL MANAGERS

**Comment by dnguyenchevy** [comment]
We need some sort of indication when a movie hasn't been released and/or still in theatre. Should we have any indication? 

If we aren't going to include movies that are still in theatre or haven't been released on DVD/BluRay, we should update requirements to reflect this.

**Comment by sammygutierrez** [comment]
:+1: @Nino55N owes me :beer:

**Comment by PhilipRead** [comment]
@dnguyenchevy Are you sure about that? The current requirements seem pretty solid to me. @mseipel What do you think?

**Comment by PhilipRead** [comment]
+1 Don't make me regret this.

**Comment by mseipel** [comment]
@dnguyenchevy @PhilipRead The current requirements encapsulate this inquiry.
+1

**Comment by sammygutierrez** [comment]
Merge your shit @Nino55N

**Pull request merged**
