### PR TITLE
PhilFav Added crucial fix.

### PR DESCRIPTION
**Pull request by PhilipRead**

### CODE REVIEW

**Comment by dnguyenchevy** [comment]
I don't think this fits our requirement. 

Can you confirm @sammygutierrez @Nino55N @mseipel ?

**Comment by mseipel** [comment]
+1 Phil.  I like it.

**Comment by PhilipRead** [comment]
FINE, I'll change it.

**Comment by mseipel** [comment]
I don't see any requirements @dnguyenchevy

**Comment by sammygutierrez** [comment]
@mseipel Added issue https://github.com/sammygutierrez/movie-list/issues/2

**Comment by dnguyenchevy** [comment]
Can we agree to make a high, medium, low priority bucket for our movies?

**Comment by sammygutierrez** [comment]
@dnguyenchevy Please create a new issue for discussion.

**Comment by mseipel** [comment]
@PhilipRead i recant my +1 from before

**Comment by PhilipRead** [comment]
Until the issue #2 is resolved I will need close this request.

**Pull request closed without merging**
