### PR TITLE
:arrow_forward: Kung Pow! Enter the Fist

### PR DESCRIPTION
**Pull request by dnguyenchevy**
let update! I support ISIS.

### CODE REVIEW

**Comment by PhilipRead** [comment]
-1 for cheating.

**Comment by sammygutierrez** [comment]
needs better description, i was really ocnfusefd

**Comment by mseipel** [comment]
+1 for commit, -1 for supporting ISIS

**Comment by dnguyenchevy** [comment]
off you guys I'm merging

**Pull request merged**
