### PR TITLE
GLADIATOR

### PR DESCRIPTION
**Pull request by sammygutierrez**
GLADIATOR

### CODE REVIEW

**Comment by mseipel** [comment]
+1

**Comment by dnguyenchevy** [comment]
+1 +1 +1 +1

**Comment by Nino55N** [comment]
:disco_parrot
+1

**Comment by PhilipRead** [comment]
http://media3.giphy.com/media/FX3OLJAUhOZNK/giphy.gif

**Comment by mseipel** [comment]
Merge it @sammygutierrez

**Pull request merged**
