### PR TITLE
Added The Shawshank Redemption

### PR DESCRIPTION
**Pull request by sammygutierrez**
One of my personal favorites.

### CODE REVIEW

**Comment by sammygutierrez** [comment]
+1, need one more

**Comment by sammygutierrez** [comment]
+1, please merge

**Comment by PhilipRead** [comment]
+10000000000000000000000000000000000000000000000
image

**Comment by sammygutierrez** [comment]
@sammygutierrez sweet, thanks

**Comment by PhilipRead** [comment]
You sneaky bastard

**Pull request merged**
